### ISSUE TITLE
Can not build on Windows

### ISSUE THREAD

**Issue by ngvlongit1** [BurntSushi/rure-go#4]
Hi
I can't seem to build my current project under windows 10.
This is error

**Comment by BurntSushi** [comment]
I see no details about your problem or how to reproduce it, so I can't help you.

**Comment by ngvlongit1** [comment]
> I see no details about your problem or how to reproduce it, so I can't help you.
Sorry about that, I submit the detail.

![2020-12-01_9-03-22](https://user-images.githubusercontent.com/3301598/100691354-1d652180-33bb-11eb-84d8-1827ec86ac23.png)

**Comment by ngvlongit1** [comment]
@BurntSushi Sorry. I have summit the error message. Can you check it for me?

**Comment by BurntSushi** [comment]
You didn't provide what I asked for. So no. Please provide reproduction steps. Like I asked originally.

Please consider reading up on how to file a bug report: https://marker.io/blog/write-bug-report/ is a decent guide
