### ISSUE TITLE
Can not build in Windows 10

### ISSUE THREAD

**Issue by ngvlongit1** [BurntSushi/rure-go#5]
Hi
I can't seem to build my current project under windows 10.
![2020-12-01_9-03-22](https://user-images.githubusercontent.com/3301598/100691421-45548500-33bb-11eb-8c06-3a1fa77d33b6.png)

**Comment by BurntSushi** [comment]
Please stop opening bug reports if you aren't going to provide enough information. If you have information to add, then add it to one of your existing bug reports.

**Comment by ngvlongit1** [comment]
@BurntSushi Sorry. I have summit the detail to https://github.com/BurntSushi/rure-go/issues/4
Please check it. Thanks
