### ISSUE TITLE
Go repository fails to display documentation

### ISSUE THREAD

**Issue by darach** [BurntSushi/rure-go#8]
The go package repository is citing inability to verify LICENSE details
and not displaying the documentation. This might make it hard for golang
programmers to get running.

Loving the perf difference, great work!

Here's the URL:

https://pkg.go.dev/github.com/BurntSushi/rure-go@v0.0.0-20200220204551-0338b655c065

Screengrab

![Screenshot 2023-09-28 at 14 08 21](https://github.com/BurntSushi/rure-go/assets/229042/821ecc4a-2990-437c-9b9a-131ba253b399)

Cheers,

Darach.

**Comment by BurntSushi** [comment]
I'm aware. This is a bug for pkg.go.dev, not here. This project is dual licensed, so pkg.go.dev should be able to use it under the terms of the MIT.
